-- Bu servis suraya kadar Flyway kullanmiyordu, semasi Hibernate ddl-auto: update
-- ile senkronize ediliyordu (bkz. entities/concretes/Address.java, ContactMedium.java,
-- inbox/Inbox.java). Bu migration iki amaca hizmet eder:
--   1) Fresh/bos bir DB'de (yeni ortam, CI) semayi sifirdan doğru kurar.
--   2) Halihazirda Hibernate'in olusturdugu, dolu bir DB'de ise hicbir sey
--      yapmaz - application*.yml'deki spring.flyway.baseline-on-migrate=true
--      + baseline-version=1 sayesinde bu surum "zaten uygulanmis" sayilir ve
--      CALISTIRILMAZ. CREATE TABLE IF NOT EXISTS yine de ekstra bir guvenlik
--      agi (bkz. infra/debezium/outbox-table.sql'deki ayni idiom).
--
-- Tablo/kolon adlari Spring Boot'un varsayilan fiziksel isimlendirme stratejisi
-- ile turetilmistir (@Table(name="ADDR") -> addr, camelCase alanlar -> snake_case).

CREATE TABLE IF NOT EXISTS addr (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_id       BIGINT       NOT NULL,
    data_type_id BIGINT       NOT NULL,
    is_active    BOOLEAN      NOT NULL DEFAULT true,
    cdate        TIMESTAMP    NOT NULL,
    cuser        VARCHAR(255) NOT NULL,
    udate        TIMESTAMP,
    uuser        VARCHAR(255),
    city_id      BIGINT       NOT NULL,
    street_name  VARCHAR(200) NOT NULL,
    house_name   VARCHAR(100) NOT NULL,
    addr_desc    VARCHAR(200) NOT NULL,
    is_primary   BOOLEAN      NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_addr_row_data_type ON addr (row_id, data_type_id);

CREATE TABLE IF NOT EXISTS cntc_medium (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_id               BIGINT       NOT NULL,
    data_type_id         BIGINT       NOT NULL,
    is_active            BOOLEAN      NOT NULL DEFAULT true,
    cdate                TIMESTAMP    NOT NULL,
    cuser                VARCHAR(255) NOT NULL,
    udate                TIMESTAMP,
    uuser                VARCHAR(255),
    cntc_data            VARCHAR(100) NOT NULL,
    cntc_medium_type_id  BIGINT       NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_cntc_medium_row_data_type ON cntc_medium (row_id, data_type_id);

-- Inbox: idempotent consumer (CustomerEventListener - "customer-events" topic'i).
-- shared-events'teki InboxEvent DEGIL, bu servise ozel yerel entity (bkz. inbox/Inbox.java).
CREATE TABLE IF NOT EXISTS inbox (
    event_id     UUID PRIMARY KEY,
    event_type   VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP    NOT NULL DEFAULT now()
);
