server:
  port: 8888
  shutdown: graceful

spring:
  application:
    name: config-server
  lifecycle:
    timeout-per-shutdown-phase: 20s
  cloud:
    config:
      server:
        git:
          uri: https://github.com/u210709011/CONFIG_Etiya-11-Akademi-CRM.git
          search-paths: configs/{application}/
          default-label: main
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${TEMPO_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
